version: '2'
services: 
  web:
    depends_on:
      - db
    build: .
    ports:
     - "5000:5000"
  traccar:
    hostname: traccar
    volumes: 
     - ./traccar.xml:/opt/traccar/conf/traccar.xml 
    image: traccar/traccar
    ports:
     - "8082:8082"
    depends_on:
      - db
  db:
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    image: postgres:13.0
    ports: 
      - "5432-5432"
 

